---
title: Ex-19-5626
date: 2025-04-29
author: Your Name
cell_count: 6
score: 5
---

```python
#created at 20250416
```


```python
#Polymorphism
```


```python
print("\n === Polymorphism ===")
```

    
     === Polymorphism ===



```python
class Shape:
    def area(self):
        pass

class Rectangle(Shape):
    def __init__(self, width, height):
            self.width = width
            self.height = height

    def area(self):
        return self.height * self.width

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius


    def area(Self):
        return 3.14 * self.radius ** 2
        
```


```python
shapes = [Rectangle(4, 3), Circle(4)]
for shape in shapes:
    print(f"Area:{shape.area()}")
```

    Area:12



    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    Cell In[3], line 3
          1 shapes = [Rectangle(4, 3), Circle(4)]
          2 for shape in shapes:
    ----> 3     print(f"Area:{shape.area()}")


    Cell In[2], line 19, in Circle.area(Self)
         18 def area(Self):
    ---> 19     return 3.14 * self.radius ** 2


    NameError: name 'self' is not defined



```python

```


---
**Score: 5**