---
title: Ex-6-7131
date: 2025-04-29
author: Your Name
cell_count: 9
score: 5
---

```python
#creatd at 20250314
```


```python
#https://stevejoe1412.gitbook.io/ssn/python-subtopics/8.-coroutines
```


```python
#Coroutine with Exception Handling
```


```python
def exception_handling_coroutine():
    try: 
        while True :
            value = yield
            print(f"received :{value}")

    except ValueError as e:
        print(f"Caught exception: {e}")
```


```python
coro = exception_handling_coroutine()
```


```python
next(coro)
```


```python
coro.send(10)
```

    received :10



```python
coro.throw(ValueError, "an error occured")
```

    /tmp/ipykernel_8692/1015842093.py:1: DeprecationWarning: the (type, exc, tb) signature of throw() is deprecated, use the single-arg signature instead.
      coro.throw(ValueError, "an error occured")


    Caught exception: an error occured



    ---------------------------------------------------------------------------

    StopIteration                             Traceback (most recent call last)

    Cell In[5], line 1
    ----> 1 coro.throw(ValueError, "an error occured")


    StopIteration: 



```python

```


---
**Score: 5**